// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nafsih/Companion.tsx": () => import("../components/mockups/nafsih/Companion.tsx"),
  "./components/mockups/nafsih/Home.tsx": () => import("../components/mockups/nafsih/Home.tsx"),
  "./components/mockups/nafsih/Journal.tsx": () => import("../components/mockups/nafsih/Journal.tsx"),
  "./components/mockups/nafsih/Library.tsx": () => import("../components/mockups/nafsih/Library.tsx"),
  "./components/mockups/nafsih/Welcome.tsx": () => import("../components/mockups/nafsih/Welcome.tsx")
};
